### ISSUE TITLE
Encrypted message length is invalid

### ISSUE THREAD

**Issue by giovariot** [Leone25/zanichelli-downloader#47]
Provando ad utilizzare il programma su macOS vado incontro a queso errore

```
Detecting reader...
Kitaboo book detected
Exchangin usertoken...
Fetching book details...
Obtaining encryption encryption key...
Fetching encrypted encryption key...
Processing...
Decrypting encryption key...
/Users/giova/Downloads/zanichelli-downloader-main/node_modules/node-forge/lib/rsa.js:578
    var error = new Error('Encrypted message length is invalid.');
                ^

Error: Encrypted message length is invalid.
    at pki.rsa.decrypt (/Users/giova/Downloads/zanichelli-downloader-main/node_modules/node-forge/lib/rsa.js:578:17)
    at key.decrypt (/Users/giova/Downloads/zanichelli-downloader-main/node_modules/node-forge/lib/rsa.js:1274:21)
    at downloadKitabooBook (file:///Users/giova/Downloads/zanichelli-downloader-main/index.js:116:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///Users/giova/Downloads/zanichelli-downloader-main/index.js:466:3 {
  length: 9,
  expected: 128
}

Node.js v22.9.0
```

**Comment by giovariot** [comment]
Ho riprovato anche oggi: stesso errore. 

Il libro è questo:
```
┌───────────────┬─────────────────────────────────────────┐
│ (index)       │ title                                   │
├───────────────┼─────────────────────────────────────────┤
│ 9788808820372 │ 'Harrison Principi di Medicina interna' │
└───────────────┴─────────────────────────────────────────┘
```

**Comment by valeriasona** [comment]
Ho il tuo stesso problema. Come hai risolto?

**Comment by Leone25** [comment]
a naso, il problema qua é che gli epub non sono criptati e non sono supportati dallo script, e non essendo supportati il sito risponde con `Not Found` che é giusto giusto 9 caratteri

se questo é il caso, non posso aiutarvi molto, se qualcuno volesse può scrivermi in privato su bluesky a @enrico.wtf e magari qualcosa si può fare, ma non prometto niente...
