### ISSUE TITLE
A repeat here but Logged in as Undefined Undefined

### ISSUE THREAD

**Issue by DavidHaynesHasGitHub** [Leone25/zanichelli-downloader#49]
Logging in...
(node:23392) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Fetching available books...
Logged in as: undefined undefined
file:///C:/Users/**********/Downloads/zanichelli-downloader-main/index.js:408
                if (response.data.pagination.pages == 0) {
                                  ^

TypeError: Cannot read properties of undefined (reading 'pagination')
    at file:///C:/Users/*************/Downloads/zanichelli-downloader-main/index.js:408:21
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Trying to access kitaboo not sure if that would make a difference. I have reset the password twice now based on the other threads on this issue.  I didnt see any direction from the other issues reported on this.

**Comment by NioBee** [comment]
Get the same error, when logging in it cannot fetch the books list:
`Logging in...
Fetching available books...
Logged in as: undefined undefined
file:///C:/zanichelli-downloader-main/index.js:408
                if (response.data.pagination.pages == 0) {
                                  ^

TypeError: Cannot read properties of undefined (reading 'pagination')
    at file:///C:/zanichelli-downloader-main/index.js:408:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`
